
services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finaldb
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nextjs_c:
    container_name: nextjs_c
    image: nextjs_img:14.2.3
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/app/postgres-data
    ports:
      - "3000:3000"
    environment:
      - DOCKER_POSTGRES_PRISMA_URL=postgresql://postgres:postgres@db:5432/finaldb?schema=public
volumes:
  postgres-data: